-- MySQL Script generated by MySQL Workbench
-- jue 01 sep 2016 12:17:11 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema geshotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema geshotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geshotel` DEFAULT CHARACTER SET utf8 ;
USE `geshotel` ;

-- -----------------------------------------------------
-- Table `geshotel`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geshotel`.`categoria` (
  `idcategoria` INT(11) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `idcategoria_UNIQUE` (`idcategoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geshotel`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geshotel`.`hotel` (
  `idhotel` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `ciudad` VARCHAR(45) NULL,
  `categoria` INT(11) NULL,
  PRIMARY KEY (`idhotel`),
  UNIQUE INDEX `idhotel_UNIQUE` (`idhotel` ASC),
  INDEX `fk_hotel_categoria1_idx` (`categoria` ASC),
  CONSTRAINT `fk_hotel_categoria1`
    FOREIGN KEY (`categoria`)
    REFERENCES `geshotel`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geshotel`.`habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geshotel`.`habitacion` (
  `idhabitacion` INT(11) NOT NULL,
  `hotel` INT(11) NULL,
  PRIMARY KEY (`idhabitacion`),
  UNIQUE INDEX `idhabitacion_UNIQUE` (`idhabitacion` ASC),
  INDEX `fk_habitacion_hotel1_idx` (`hotel` ASC),
  CONSTRAINT `fk_habitacion_hotel1`
    FOREIGN KEY (`hotel`)
    REFERENCES `geshotel`.`hotel` (`idhotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geshotel`.`huesped`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geshotel`.`huesped` (
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `fechaNac` DATETIME NULL,
  `poblacion` VARCHAR(45) NULL,
  `habitacion` INT(11) NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  INDEX `fk_huesped_habitacion1_idx` (`habitacion` ASC),
  CONSTRAINT `fk_huesped_habitacion1`
    FOREIGN KEY (`habitacion`)
    REFERENCES `geshotel`.`habitacion` (`idhabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
