/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.Operaciones;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Habitacion;
import modelo.Hotel;

/**
 *
 * @author vesprada
 */

public class añadirHabitacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form añadirHabitacion
     */
    
    private Operaciones oper;
    private List<Hotel> listHotels = null;
    private Hotel hotel = null;
    
    private List<Habitacion> listHabitacion = null;
    private Habitacion habitacion = null;
    
    
    public añadirHabitacion(Operaciones oper) {
        initComponents();
        jComboHabitacionNueva.removeAllItems();
        txtIdHotelesNuevaHabitacion.setEnabled(false);
        txtIdHotelesNuevaHabitacion.setText("");
        this.oper = oper;
        listHotels = oper.showHotelList();
        llenaHoteles(listHotels);
        hotel = new Hotel();
        listHabitacion = oper.habitacionList();
        txtIdHotelesNuevaHabitacion.setText(""+(listHabitacion.size()+1));
    }
    
    
    public void llenaHoteles(List<Hotel> listHotel){
        for (int x = 0 ; x < listHotel.size() ; x++){
            hotel= listHotel.get(x);
            jComboHabitacionNueva.addItem(hotel.getNombre());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdHotelesNuevaHabitacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboHabitacionNueva = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboNumeroCamas = new javax.swing.JComboBox();
        jbtGuardarnuevaHabitacion = new javax.swing.JButton();
        jbtCancelarnuevaHabitacion = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("ID; ");

        txtIdHotelesNuevaHabitacion.setText("jTextField1");

        jLabel2.setText("Hotel; ");

        jComboHabitacionNueva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Camas; ");

        jComboNumeroCamas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        jbtGuardarnuevaHabitacion.setText("Guardar");
        jbtGuardarnuevaHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarnuevaHabitacionActionPerformed(evt);
            }
        });

        jbtCancelarnuevaHabitacion.setText("Cancelar");
        jbtCancelarnuevaHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarnuevaHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboNumeroCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdHotelesNuevaHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboHabitacionNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtGuardarnuevaHabitacion)
                        .addGap(49, 49, 49)
                        .addComponent(jbtCancelarnuevaHabitacion)
                        .addGap(81, 81, 81)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdHotelesNuevaHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboHabitacionNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboNumeroCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCancelarnuevaHabitacion)
                    .addComponent(jbtGuardarnuevaHabitacion))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtGuardarnuevaHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarnuevaHabitacionActionPerformed
        habitacion = new Habitacion();
        habitacion.setIdhabitacion(Integer.parseInt(txtIdHotelesNuevaHabitacion.getText()));
        hotel = new Hotel();
        hotel.setIdhotel(jComboHabitacionNueva.getSelectedIndex()+1);
        habitacion.setHotel(hotel);
        habitacion.setNumcamas(jComboNumeroCamas.getSelectedIndex()+1);
        oper.insertNewHabitacion(habitacion);
        JOptionPane.showMessageDialog(null, "Insert new room correctly.");
        this.dispose();
    }//GEN-LAST:event_jbtGuardarnuevaHabitacionActionPerformed

    private void jbtCancelarnuevaHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarnuevaHabitacionActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtCancelarnuevaHabitacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboHabitacionNueva;
    private javax.swing.JComboBox jComboNumeroCamas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtCancelarnuevaHabitacion;
    private javax.swing.JButton jbtGuardarnuevaHabitacion;
    private javax.swing.JTextField txtIdHotelesNuevaHabitacion;
    // End of variables declaration//GEN-END:variables
}
