/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Operaciones;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.Habitacion;
import modelo.Hotel;
import modelo.Huesped;

/**
 *
 * @author terrorist
 */
public class hoteles extends javax.swing.JInternalFrame {

    /**
     * Creates new form hoteles
     */
    
    
    
    private List<Hotel> listHotels = null;
    private Hotel hotel = null;
    
    private Operaciones oper ;    
    private int pointerHotel;
    
    private List<Categoria> listCategoria = null;
    private Categoria categoria;
    
    private boolean modifyNew = false;
    private boolean checkFieldsHotel = false;
    
    private DefaultTableModel dtm = null;     
    private DefaultListModel dlm = null;   
    
    
    public hoteles(Operaciones oper) {
        initComponents();
        cleanValues();
        enabledTxt(false);
        this.oper = oper;
        listHotels = oper.showHotelList();
        txtTotalNumberHotels.setText(""+listHotels.size());
        txtPointerHotel.setText(""+1);        
        showValuesHotelList(listHotels, 0);
        txtPointerHotel.setEnabled(false);
        txtTotalNumberHotels.setEnabled(false);
        listCategoria = oper.categoriaList();
        jbtGuardarhotel.setEnabled(false);
        jbtCancelarHotel.setEnabled(false);
        jComboBoxCategoryHotel.removeAllItems();
        putCategories(listCategoria);        
        putHotelsOnTable();
    }
    
    
    public void putHotelsOnTable(){
        dtm = new DefaultTableModel();
        String [] columnas = {"ID", "NOMBRE", "CIUDAD"};
        dtm.setColumnIdentifiers(columnas);
        dtm.setNumRows(0);
        tabla.setModel(dtm);
        listHotels = oper.showHotelList();
        for (int i = 0; i < listHotels.size(); i++) {
            hotel= listHotels.get(i);
            Object[] v = new Object[3];//numero de columnas
            v[0] = hotel.getIdhotel();
            v[1] = hotel.getNombre();
            v[2] = hotel.getCiudad();
            dtm.addRow(v);            
        }
    }
    
    
    public void putCategories(List<Categoria> listCategoria){
        for(int x =0 ; x < listCategoria.size() ; x++){
            categoria= listCategoria.get(x);
            jComboBoxCategoryHotel.addItem(categoria.getDescripcion());
        }
    }
    
    
    public void cleanValues(){
        txtIdHotel.setText("");
        txtNameHotel.setText("");
        txtCityHotel.setText("");        
        txtPointerHotel.setText("");
        txtTotalNumberHotels.setText("");
    }
    
    
    public void enabledTxt(boolean pass){
        txtIdHotel.setEnabled(pass);
        txtNameHotel.setEnabled(pass);
        txtCityHotel.setEnabled(pass);
        jComboBoxCategoryHotel.setEnabled(pass);
    }
    
    public void activaCursores(boolean pass){
        jbtFirstHotel.setEnabled(pass);
        jbtPreviousHotel.setEnabled(pass);
        jbtNextHotel.setEnabled(pass);
        jbtLastHotel.setEnabled(pass);
    }
    
    
    
    public void showValuesHotelList(List<Hotel> listHotels, int pointer){
        Categoria cate = new Categoria();        
        pointerHotel = pointer;
        hotel = null;
        hotel = listHotels.get(pointerHotel);
        txtIdHotel.setText(""+hotel.getIdhotel());
        txtNameHotel.setText(hotel.getNombre());
        txtCityHotel.setText(hotel.getCiudad());
        txtPointerHotel.setText("" + (pointerHotel+1));
        txtTotalNumberHotels.setText(""+listHotels.size());
        ///////////////////////////////////////////////////////////////////////////////////
        jComboBoxCategoryHotel.setSelectedIndex((hotel.getCategoria().getIdcategoria()-1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdHotel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNameHotel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCityHotel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtFirstHotel = new javax.swing.JButton();
        jbtPreviousHotel = new javax.swing.JButton();
        jbtNextHotel = new javax.swing.JButton();
        jbtLastHotel = new javax.swing.JButton();
        txtPointerHotel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotalNumberHotels = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbtNuevoHotel = new javax.swing.JButton();
        jbtModificaHoteles = new javax.swing.JButton();
        jbtEliminarHotel = new javax.swing.JButton();
        jbtCancelarHotel = new javax.swing.JButton();
        jbtGuardarhotel = new javax.swing.JButton();
        jComboBoxCategoryHotel = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hotel information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("ID; ");

        jLabel2.setText("NAME; ");

        txtNameHotel.setText("jTextField2");

        jLabel3.setText("CITY; ");

        txtCityHotel.setText("jTextField3");

        jLabel4.setText("CATEGORY; ");

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtFirstHotel.setText("|<");
        jbtFirstHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFirstHotelActionPerformed(evt);
            }
        });

        jbtPreviousHotel.setText("<");
        jbtPreviousHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPreviousHotelActionPerformed(evt);
            }
        });

        jbtNextHotel.setText(">");
        jbtNextHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNextHotelActionPerformed(evt);
            }
        });

        jbtLastHotel.setText(">|");
        jbtLastHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLastHotelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jbtFirstHotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtPreviousHotel)
                .addGap(18, 18, 18)
                .addComponent(jbtNextHotel)
                .addGap(18, 18, 18)
                .addComponent(jbtLastHotel)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtFirstHotel)
                    .addComponent(jbtPreviousHotel)
                    .addComponent(jbtNextHotel)
                    .addComponent(jbtLastHotel))
                .addContainerGap())
        );

        txtPointerHotel.setText("jTextField5");

        jLabel5.setText("/");

        txtTotalNumberHotels.setText("jTextField6");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hotel_Icon.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtNuevoHotel.setText("Nuevo");
        jbtNuevoHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNuevoHotelActionPerformed(evt);
            }
        });

        jbtModificaHoteles.setText("Modificar");
        jbtModificaHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModificaHotelesActionPerformed(evt);
            }
        });

        jbtEliminarHotel.setText("Eliminar");
        jbtEliminarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEliminarHotelActionPerformed(evt);
            }
        });

        jbtCancelarHotel.setText("Cancelar");
        jbtCancelarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarHotelActionPerformed(evt);
            }
        });

        jbtGuardarhotel.setText("Guardar");
        jbtGuardarhotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarhotelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtNuevoHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtModificaHoteles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtEliminarHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtCancelarHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtGuardarhotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jbtNuevoHotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtModificaHoteles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtEliminarHotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCancelarHotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jbtGuardarhotel)
                .addContainerGap())
        );

        jComboBoxCategoryHotel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCategoryHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtIdHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 255, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtCityHotel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                            .addComponent(txtNameHotel, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 67, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(txtPointerHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalNumberHotels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNameHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCityHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxCategoryHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPointerHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtTotalNumberHotels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.setEnabled(false);
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtPreviousHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPreviousHotelActionPerformed
        if(pointerHotel==0){
            JOptionPane.showMessageDialog(null, "It´s the first hotel");
        }else{
            showValuesHotelList(listHotels, (pointerHotel-1));
        }
    }//GEN-LAST:event_jbtPreviousHotelActionPerformed

    private void jbtFirstHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFirstHotelActionPerformed
        if(pointerHotel==0){
            JOptionPane.showMessageDialog(null, "It´s the first hotel");
        }else{            
            showValuesHotelList(listHotels, 0);
        }
       
    }//GEN-LAST:event_jbtFirstHotelActionPerformed

    private void jbtNextHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNextHotelActionPerformed
        if(pointerHotel==(listHotels.size()-1)){
            JOptionPane.showMessageDialog(null, "This is the last hotel");
        }else{
            showValuesHotelList(listHotels, (pointerHotel+1));
        }
    }//GEN-LAST:event_jbtNextHotelActionPerformed

    private void jbtLastHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLastHotelActionPerformed
        if(pointerHotel==(listHotels.size()-1)){
            JOptionPane.showMessageDialog(null, "This is the last hotel");
        }else{
            showValuesHotelList(listHotels, (listHotels.size()-1));
        }
    }//GEN-LAST:event_jbtLastHotelActionPerformed

    //Method modify hotel Information
    private void jbtModificaHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModificaHotelesActionPerformed
        modifyNew = false;
        enabledTxt(true);
        txtIdHotel.setEnabled(false);
        jbtNuevoHotel.setEnabled(false);
        jbtModificaHoteles.setEnabled(false);
        jbtEliminarHotel.setEnabled(false);
        jbtGuardarhotel.setEnabled(true);
        jbtCancelarHotel.setEnabled(true);
        activaCursores(false);
    }//GEN-LAST:event_jbtModificaHotelesActionPerformed

    //New hotel button--Work correctly
    private void jbtNuevoHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNuevoHotelActionPerformed
        enabledTxt(true);
        cleanValues();
        modifyNew = true;
        txtIdHotel.setText(""+(listHotels.size()+1)); 
        txtPointerHotel.setText(""+(listHotels.size()+1));
        txtTotalNumberHotels.setText(""+(listHotels.size()+1));
        jbtNuevoHotel.setEnabled(false);
        jComboBoxCategoryHotel.setSelectedIndex(0);
        jbtModificaHoteles.setEnabled(false);
        jbtEliminarHotel.setEnabled(false);
        jbtCancelarHotel.setEnabled(true);
        jbtGuardarhotel.setEnabled(true);
        txtIdHotel.setEnabled(false);
        activaCursores(false);
    }//GEN-LAST:event_jbtNuevoHotelActionPerformed

    //Method cancel button--Work correctly
    private void jbtCancelarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarHotelActionPerformed
        enabledTxt(false);
        //listHotels = null;
        listHotels = oper.showHotelList();
        showValuesHotelList(listHotels, 0);
        modifyNew = false;
        jbtNuevoHotel.setEnabled(true);
        jbtModificaHoteles.setEnabled(true);
        jbtEliminarHotel.setEnabled(true);
        jbtCancelarHotel.setEnabled(false);
        jbtGuardarhotel.setEnabled(false);
        activaCursores(true);        
        putHotelsOnTable();
    }//GEN-LAST:event_jbtCancelarHotelActionPerformed
    //Method to save information of hotels--Work correctly
    private void jbtGuardarhotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarhotelActionPerformed
            boolean prueba = checkFieldsMethod();
            System.out.println("BOOLEAN"+prueba);
            if(checkFieldsMethod()){
                categoria = listCategoria.get(jComboBoxCategoryHotel.getSelectedIndex());
                hotel = null;
                hotel = new Hotel();
                hotel.setIdhotel(Integer.parseInt(txtIdHotel.getText()));
                hotel.setCategoria(categoria);
                hotel.setNombre(txtNameHotel.getText());
                hotel.setCiudad(txtCityHotel.getText());
                if(modifyNew){
                    oper.insertNewHotel(hotel);                    
                }else{
                    oper.updateHotel(hotel);                    
                }
            }
            putHotelsOnTable();
            jbtCancelarHotelActionPerformed(evt);
            
    }//GEN-LAST:event_jbtGuardarhotelActionPerformed

    private void jbtEliminarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEliminarHotelActionPerformed
       if(listHotels.size()<2){
           JOptionPane.showMessageDialog(null, "This is the last hotel, you cant delete this.");
       }else{
           JDialog.setDefaultLookAndFeelDecorated(true);
            int response = JOptionPane.showConfirmDialog(null, "Do you really want to delete this hotel", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.NO_OPTION) {
                jbtCancelarHotelActionPerformed(evt);
            }else if (response == JOptionPane.YES_OPTION) {
                //borrar primero los huespedes
                //borrar habitaciones
                //borrar hoteles
                List<Habitacion> listRooms;
                Habitacion room;
                List<Huesped> listClients;
                Huesped huespedAux;
                int hotel = Integer.parseInt(txtIdHotel.getText());
                listRooms=oper.showRoomListOnHotels(hotel);
                if(listRooms.size()>0){
                    System.out.println("EL TAMAÑO DE LA LISTA DE LAs HABITACIONES ES; "+listRooms.size());
                    for(int x = 0 ; x< listRooms.size() ; x++){
                        room=listRooms.get(x);
                        listClients=oper.searchClientByRoom(room.getIdhabitacion());
                        System.out.println("EL TAMAÑO DE LA LISTA DE HUESPEDES EN ESA HABITACION ES; "+listClients.size());
                        for(int y = 0 ; y <listClients.size() ; y++){
                            huespedAux=listClients.get(y);
                            System.out.println("NOMBRE DEL HUESPED; "+huespedAux.getNombre());
                            huespedAux.setHabitacion(null);
                            System.out.println("EL HUESPED "+huespedAux.getNombre()+"PONEMOS SU HABITACION A"+huespedAux.getHabitacion());
                            System.out.println("ACTUALIZAMOS INFO DEL HUESPED");
                            oper.updateClientInformation(huespedAux);
                            System.out.println("PODEMOS IR CON AL NULL DE LA HABITACION");
                        }
                        room.setHotel(null);
                        System.out.println("LA HABITACION CON ID "+room.getIdhabitacion()+"PROCEDE A ACTUALIZARSE");
                        System.out.println("PONEMOS EL CAMPO HOTEL DE LA HABITACION A "+room.getHotel());
                        oper.updateHabitacion(room);
                        System.out.println("PODEMOS ELIMINAR LA HABITACION"+room.getIdhabitacion());
                        oper.deleteHabitacion(room);
                        System.out.println("SE HA HECHO LA ACTUALIZACION DE LA HABITACION");
                        System.out.println("SE PUEDE BORRAR EL HOTEL ");
                    }
                }
                oper.deleteHotel(Integer.parseInt(txtIdHotel.getText()));
            }else if (response == JOptionPane.CLOSED_OPTION) { 
                jbtCancelarHotelActionPerformed(evt);
            }
       }
        jbtCancelarHotelActionPerformed(evt);
    }//GEN-LAST:event_jbtEliminarHotelActionPerformed

    private boolean checkFieldsMethod(){ 
        if(txtNameHotel.getText().equals("")||(txtCityHotel.equals(""))){            
            if(txtNameHotel.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please, insert a name for a new Hotel.");
                txtNameHotel.requestFocus();                    
            }else{
                checkFieldsHotel= true;
            }    
            if(txtCityHotel.getText().equals("")&&checkFieldsHotel==true){
                JOptionPane.showMessageDialog(null, "Please, insert a name of the city.");
                txtCityHotel.requestFocus();               
            }else{
                checkFieldsHotel= true;
            }
        }else{
            checkFieldsHotel = true;
        }           
        return checkFieldsHotel;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxCategoryHotel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCancelarHotel;
    private javax.swing.JButton jbtEliminarHotel;
    private javax.swing.JButton jbtFirstHotel;
    private javax.swing.JButton jbtGuardarhotel;
    private javax.swing.JButton jbtLastHotel;
    private javax.swing.JButton jbtModificaHoteles;
    private javax.swing.JButton jbtNextHotel;
    private javax.swing.JButton jbtNuevoHotel;
    private javax.swing.JButton jbtPreviousHotel;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCityHotel;
    private javax.swing.JTextField txtIdHotel;
    private javax.swing.JTextField txtNameHotel;
    private javax.swing.JTextField txtPointerHotel;
    private javax.swing.JTextField txtTotalNumberHotels;
    // End of variables declaration//GEN-END:variables
}
