/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
CHECK DATECHOOSER CONFIGURATION
*/



package vista;

import controlador.Operaciones;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.Huesped;

/**
 *
 * @author terrorist
 */

public class huespedes extends javax.swing.JInternalFrame {

    /**
     * Creates new form huespedes
     */
    
    private List<Huesped> listClients;
    private List<Huesped> listCopy;
    private Huesped client;
    private int pointerClient;
    private Calendar calendar  = GregorianCalendar.getInstance();
    private Operaciones oper;
    private boolean check= false;
    
    
    public huespedes(Operaciones oper) {
        initComponents();
        cleanValuesOfTxt();
        enableYesNoTxt(false);        
        this.oper = oper;
        pointerHuesped.setEnabled(false);        
        pointerSizeHuesped.setEnabled(false);
        pointerHuesped.setText(""+1);
        pointerClient = 0;
        //Instance of oper
        listClients = oper.showGuestList();
        //Put the size of list of clients on txt
        pointerSizeHuesped.setText(""+listClients.size());
        //Send listClients to method to show
        showInformationClients(listClients, pointerClient);
        activaBotonesmodificacion(false);
    }
    
    
    public void activaBotonesmodificacion(boolean pass){
        jbtdeleteClientInformation.setEnabled(pass);
        jbtsaveChangesClientInformation.setEnabled(pass);
        jbtcancelChangesClientInformation.setEnabled(pass);
    }
    
    
    public void cleanValuesOfTxt(){
        //This method clean of values the txt of clients
        txtDnihuesped.setText("");
        txtNombreHuesped.setText("");
        txtApellidoshuesped.setText("");
        txtPoblacionHuesped.setText("");
        txtDireccionHuesped.setText("");
    }
    
    
    public void enableYesNoTxt(boolean pass){
        //This method change to enable or not the txt of information of the clients
        txtDnihuesped.setEnabled(pass);
        txtNombreHuesped.setEnabled(pass);
        txtApellidoshuesped.setEnabled(pass);
        txtDireccionHuesped.setEnabled(pass);
        txtPoblacionHuesped.setEnabled(pass);        
    }
    
    
    
    
    //This method get list of client --Work correctly
    public void showInformationClients(List<Huesped> listClients, int pointer){
        this.pointerClient = pointer;
        client = null;
        client = listClients.get(pointerClient);
        txtDnihuesped.setText(client.getDni());
        txtNombreHuesped.setText(client.getNombre());
        txtApellidoshuesped.setText(client.getApellidos());
        txtDireccionHuesped.setText(client.getDireccion());
        //CHECK DATECHOOSERCOMBO CONFIGURATION
        //dateChooserNacimientoHuesped.setEnabled(false);
        calendar.setTime(client.getFechaNac());
        //Agree calendar in comboDateChooser
        dateChooserNacimientoHuesped.setSelectedDate(calendar);         
        txtPoblacionHuesped.setText(client.getPoblacion());        
        pointerHuesped.setText(""+(pointerClient+1));
        pointerSizeHuesped.setText(""+(listClients.size()+1));
    }
    
    
    
    //This method blocked thr cursors buttons--Work correctly
    public void blockedCursor(boolean pass){
        jbtFirstClient.setEnabled(pass);
        jbtPreviousCLient.setEnabled(pass);
        jbtNextClient.setEnabled(pass);
        jbtLastClient.setEnabled(pass);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDnihuesped = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreHuesped = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoshuesped = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccionHuesped = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateChooserNacimientoHuesped = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        txtPoblacionHuesped = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtFirstClient = new javax.swing.JButton();
        jbtPreviousCLient = new javax.swing.JButton();
        jbtNextClient = new javax.swing.JButton();
        jbtLastClient = new javax.swing.JButton();
        jbtSearchClientInformation = new javax.swing.JButton();
        pointerHuesped = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pointerSizeHuesped = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbtmodifyClientInformation = new javax.swing.JButton();
        jbtdeleteClientInformation = new javax.swing.JButton();
        jbtsaveChangesClientInformation = new javax.swing.JButton();
        jbtcancelChangesClientInformation = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Huéspedes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("DNI; ");

        txtDnihuesped.setText("jTextField1");

        jLabel2.setText("Nombre; ");

        txtNombreHuesped.setText("jTextField1");

        jLabel3.setText("Apellidos; ");

        txtApellidoshuesped.setText("jTextField1");

        jLabel4.setText("Dirección; ");

        txtDireccionHuesped.setText("jTextField1");

        jLabel5.setText("Fehca nacimiento; ");

        jLabel6.setText("Población; ");

        txtPoblacionHuesped.setText("jTextField1");
        txtPoblacionHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPoblacionHuespedActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtFirstClient.setText("|<");
        jbtFirstClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFirstClientActionPerformed(evt);
            }
        });

        jbtPreviousCLient.setText("<");
        jbtPreviousCLient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPreviousCLientActionPerformed(evt);
            }
        });

        jbtNextClient.setText(">");
        jbtNextClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNextClientActionPerformed(evt);
            }
        });

        jbtLastClient.setText(">|");
        jbtLastClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLastClientActionPerformed(evt);
            }
        });

        jbtSearchClientInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/glass.png"))); // NOI18N
        jbtSearchClientInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchClientInformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtFirstClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtPreviousCLient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSearchClientInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbtNextClient)
                .addGap(18, 18, 18)
                .addComponent(jbtLastClient)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtNextClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtFirstClient)
                        .addComponent(jbtPreviousCLient)
                        .addComponent(jbtLastClient))
                    .addComponent(jbtSearchClientInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pointerHuesped.setText("jTextField1");

        jLabel7.setText("/");

        pointerSizeHuesped.setText("jTextField1");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Clients-icon.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtmodifyClientInformation.setText("Modify");
        jbtmodifyClientInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtmodifyClientInformationActionPerformed(evt);
            }
        });

        jbtdeleteClientInformation.setText("Delete");
        jbtdeleteClientInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtdeleteClientInformationActionPerformed(evt);
            }
        });

        jbtsaveChangesClientInformation.setText("Save");
        jbtsaveChangesClientInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsaveChangesClientInformationActionPerformed(evt);
            }
        });

        jbtcancelChangesClientInformation.setText("Cancel");
        jbtcancelChangesClientInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcancelChangesClientInformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtmodifyClientInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtdeleteClientInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtsaveChangesClientInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtcancelChangesClientInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtmodifyClientInformation)
                .addGap(18, 18, 18)
                .addComponent(jbtdeleteClientInformation)
                .addGap(18, 18, 18)
                .addComponent(jbtsaveChangesClientInformation)
                .addGap(18, 18, 18)
                .addComponent(jbtcancelChangesClientInformation)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(pointerHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pointerSizeHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDnihuesped)
                                    .addComponent(txtNombreHuesped)
                                    .addComponent(txtApellidoshuesped)
                                    .addComponent(txtDireccionHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateChooserNacimientoHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPoblacionHuesped))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDnihuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellidoshuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDireccionHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dateChooserNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPoblacionHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pointerHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(pointerSizeHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtPreviousCLientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPreviousCLientActionPerformed
       if(pointerClient==0){
            JOptionPane.showMessageDialog(null, "It´s the first guest.");
        }else{
            showInformationClients(listClients, (pointerClient-1));
        }
    }//GEN-LAST:event_jbtPreviousCLientActionPerformed

    private void jbtFirstClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFirstClientActionPerformed
        if(pointerClient==0){
            JOptionPane.showMessageDialog(null, "It´s the first guest.");
        }else{            
            showInformationClients(listClients, 0);
        }
    }//GEN-LAST:event_jbtFirstClientActionPerformed

    private void jbtNextClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNextClientActionPerformed
       if(pointerClient==(listClients.size()-1)){
            JOptionPane.showMessageDialog(null, "This is the last guest.");
        }else{
            showInformationClients(listClients, (pointerClient+1));
        }
    }//GEN-LAST:event_jbtNextClientActionPerformed

    private void jbtLastClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLastClientActionPerformed
        if(pointerClient==(listClients.size()-1)){
            JOptionPane.showMessageDialog(null, "This is the last guest.");
        }else{
            showInformationClients(listClients, (listClients.size()-1));
        }
    }//GEN-LAST:event_jbtLastClientActionPerformed

    private void jbtmodifyClientInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtmodifyClientInformationActionPerformed
        enableYesNoTxt(true);
        txtDnihuesped.setEnabled(false);
        activaBotonesmodificacion(true);
    }//GEN-LAST:event_jbtmodifyClientInformationActionPerformed

    //Method to update information of the client--Work correctly
    private void jbtsaveChangesClientInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsaveChangesClientInformationActionPerformed
        if(checkFields()){
            client = new Huesped();
            client.setDni(txtDnihuesped.getText());
            client.setNombre(txtNombreHuesped.getText());
            client.setApellidos(txtApellidoshuesped.getText());
            client.setDireccion(txtDireccionHuesped.getText());
            client.setPoblacion(txtPoblacionHuesped.getText());
            client.setFechaNac(dateChooserNacimientoHuesped.getSelectedDate().getTime());
            oper.updateClientInformation(client);
            enableYesNoTxt(false);
            listClients = oper.showGuestList();
            showInformationClients(listClients, pointerClient);
        }
        JOptionPane.showMessageDialog(null, "Insert new guest correctly.");
        activaBotonesmodificacion(false);
    }//GEN-LAST:event_jbtsaveChangesClientInformationActionPerformed

    //This method check the user has inserted all the information of the new client
    public boolean checkFields(){
       if(txtNombreHuesped.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please insert a name of new guest.");
            txtNombreHuesped.requestFocus();
        }else if(txtApellidoshuesped.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please insert a surname of new guest.");
            txtApellidoshuesped.requestFocus();
        }else if(txtDireccionHuesped.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please insert a adress of new guest.");
            txtDireccionHuesped.requestFocus();
        }else if(txtPoblacionHuesped.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please insert a city of new guest.");
            txtPoblacionHuesped.requestFocus();
        }else{
            check = true;
        }
        return check ;
    }
    
    
    private void txtPoblacionHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPoblacionHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoblacionHuespedActionPerformed

    
    //This method disable txt of the internalFrame--Work correctly
    private void jbtcancelChangesClientInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcancelChangesClientInformationActionPerformed
        enableYesNoTxt(false);
        jbtdeleteClientInformation.setEnabled(true);
        listClients= oper.showGuestList();
        showInformationClients(listClients, pointerClient);
        blockedCursor(true);        
        activaBotonesmodificacion(false);
        
    }//GEN-LAST:event_jbtcancelChangesClientInformationActionPerformed

    
    //This method delete a client selected-- Work correctly
    private void jbtdeleteClientInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtdeleteClientInformationActionPerformed
        if(listClients.size()<2){
           JOptionPane.showMessageDialog(null, "This is the last client, you cant delete this.");
       }else{
           JDialog.setDefaultLookAndFeelDecorated(true);
            int response = JOptionPane.showConfirmDialog(null, "Do you really want to delete this client", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.NO_OPTION) {
                jbtcancelChangesClientInformationActionPerformed(evt);
            }else if (response == JOptionPane.YES_OPTION) {
                oper.deleteCLient(txtDnihuesped.getText());
                listClients=oper.showGuestList();
                showInformationClients(listClients, pointerClient-1);
            }else if (response == JOptionPane.CLOSED_OPTION) { 
                jbtcancelChangesClientInformationActionPerformed(evt);
            }
       }
        jbtcancelChangesClientInformationActionPerformed(evt);
    }//GEN-LAST:event_jbtdeleteClientInformationActionPerformed

    
    //Method want client -- Work correctly
    private void jbtSearchClientInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchClientInformationActionPerformed
        String query = JOptionPane.showInputDialog(null,"Insert a dni or name and surname for seacrh client information.");
        /*Huesped prueba = new Huesped();
        prueba = oper.buscaHuespedString(query);
        System.out.println("PRUEBA USER IS "+prueba.getNombre()+prueba.getApellidos());*/
        
        System.out.println("STRING QUERY ;"+query);
        listCopy = oper.searchClientByDni(query);
        if(listCopy.size()==0){
            JOptionPane.showMessageDialog(null, "No results for this information.");
        }
        if(listCopy.size()>1){
            JOptionPane.showMessageDialog(null, "Find more than one result, please, especify the query.");
        }if(listCopy.size()==1){
            client = new Huesped();
            client= listCopy.get(0);
            txtDnihuesped.setText(client.getDni());
            txtNombreHuesped.setText(client.getNombre());
            txtApellidoshuesped.setText(client.getApellidos());
            txtDireccionHuesped.setText(client.getDireccion());
            calendar.setTime(client.getFechaNac());
            //Agree calendar in comboDateChooser
            dateChooserNacimientoHuesped.setSelectedDate(calendar);         
            txtPoblacionHuesped.setText(client.getPoblacion());
            pointerHuesped.setText("1");
            pointerSizeHuesped.setText("1");
            blockedCursor(false);
            jbtmodifyClientInformation.setEnabled(false);
            jbtdeleteClientInformation.setEnabled(false);
            jbtsaveChangesClientInformation.setEnabled(false);
        }        
        
        
        
        
    }//GEN-LAST:event_jbtSearchClientInformationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserNacimientoHuesped;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtFirstClient;
    private javax.swing.JButton jbtLastClient;
    private javax.swing.JButton jbtNextClient;
    private javax.swing.JButton jbtPreviousCLient;
    private javax.swing.JButton jbtSearchClientInformation;
    private javax.swing.JButton jbtcancelChangesClientInformation;
    private javax.swing.JButton jbtdeleteClientInformation;
    private javax.swing.JButton jbtmodifyClientInformation;
    private javax.swing.JButton jbtsaveChangesClientInformation;
    private javax.swing.JTextField pointerHuesped;
    private javax.swing.JTextField pointerSizeHuesped;
    private javax.swing.JTextField txtApellidoshuesped;
    private javax.swing.JTextField txtDireccionHuesped;
    private javax.swing.JTextField txtDnihuesped;
    private javax.swing.JTextField txtNombreHuesped;
    private javax.swing.JTextField txtPoblacionHuesped;
    // End of variables declaration//GEN-END:variables
}
